### ISSUE TITLE
Block auto-rotate.

### ISSUE THREAD

**Issue by julioflima** [ViralCorporation/m.nails-up#23]
@MelisseCabral

**Comment by MelisseLima** [comment]
@juloko 
My searchs until now doesnt show any solution every forum i find about the topic says we can't control this property of the device in web. So could be not feasible. Best shot its detect the rotate and alert the user about the bad functionality in landscape mode.

**Comment by julioflima** [comment]
OR
Let him responsible in that way. I'll solve them some time, when I finished the basic ones.
