### ISSUE TITLE
Animation of Bottom Navigation

### ISSUE THREAD

**Issue by julioflima** [ViralCorporation/m.nails-up#7]
@MelisseCabral 

Do the animation of bottom navigation acordding to the material/guidelines.

Source:
https://material.io/guidelines/components/bottom-navigation.html#bottom-navigation-specs

**Comment by MelisseLima** [comment]
DONE

**Comment by MelisseLima** [comment]
I have done animation using animated. I will look the guidelines.

**Comment by julioflima** [comment]
Congratulations!
