### ISSUE TITLE
Create and algorith to elaborate the content.

### ISSUE THREAD

**Issue by julioflima** [ViralCorporation/m.nails-up#9]
@MelisseCabral 

Create and algorith to show previously some text of service, and when clicked grow this.

About just show a part:
http://jsfiddle.net/zA23k/215/

Like in personal, and like the reference Julia sends:
![image](https://user-images.githubusercontent.com/17098382/28412488-bb104952-6d1a-11e7-9ee4-a2180de81d59.png)

![image](https://user-images.githubusercontent.com/17098382/28412538-ea275adc-6d1a-11e7-8e88-0b6562a4ac5f.png)

**Comment by MelisseLima** [comment]
DONE
